name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with API Key
        run: |
          echo "API Key is set: $(if [ -n \"$VITE_GOOGLE_API_KEY\" ]; then echo 'YES'; else echo 'NO'; fi)"
          npm ci && npm run build
        env:
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
      - name: Deploy Firestore Rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARNIVAL_PLANNER }}'

      - name: Deploy Storage Rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only storage
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARNIVAL_PLANNER }}'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARNIVAL_PLANNER }}'
          channelId: live
          projectId: carnival-planner
